---
label: Project
hide_body: true
fields:
- name: summary
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: posts
      file: 
      path: 
  label: summary
- name: pages
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: posts
  label: pages
pages:
- src/_data/test.json
