---
label: Project
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: datetime
  name: date
  label: date
- type: textarea
  name: status
  label: status
- name: featured
  type: blocks
  label: featured
  template_types:
  - gallery
  - youtube-embed
  config:
    min: 
    max: 
- name: contents
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: data
      file: 
      path: 
  label: contents
