---
label: Project
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  hidden: true
  default: project
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
  default: now
- type: text
  name: description
  label: description
- name: collaborators
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: collaborators
- type: textarea
  name: status
  label: status
- name: featured
  type: blocks
  label: featured
  template_types:
  - gallery
  - youtube-embed
  config:
    min: 
    max: 
- name: contents
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: posts
  label: contents
pages:
- src/pages/about.md
- src/posts/plain-white-tee.md
- src/posts/these-truths.md
