---
label: Project
hide_body: false
fields:
- name: eleventyExcludeFromCollections
  type: boolean
  label: hidden
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
  default: now
- type: text
  name: description
  label: description
- name: tags
  type: tag_list
  default: []
  label: tags
- name: social
  type: file
  config:
    maxSize: 64
  label: social
- type: textarea
  name: status
  label: status
  config:
    wysiwyg: true
    schema:
      format: markdown
- name: color
  type: color
  label: color
  config:
    required: false
    color_format: Hex
- name: featured
  type: blocks
  label: featured
  template_types:
  - gallery
  - youtube
  - audio
  config:
    min: 
    max: 
pages:
- src/projects/knots.md
- src/projects/lineweight.md
- src/projects/people-of-sol.md
- src/projects/the-book-of-words.md
- src/projects/tomorrow.md
- src/projects/we-ve-traveled-so-far.md
