---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
  default: now
- type: text
  name: description
  label: description
- name: tags
  type: tag_list
  default: []
  label: tags
- type: textarea
  name: status
  label: status
- name: featured
  type: blocks
  label: featured
  template_types:
  - gallery
  - youtube
  - audio
  config:
    min: 
    max: 
pages:
- src/pages/about.md
